const constants = {
  FETCH_DINOSAUR_REQUEST: "FETCH_DINOSAUR_REQUEST",
  FETCH_DINOSAUR_SUCCESS: "FETCH_DINOSAUR_SUCCESS",
  FETCH_DINOSAUR_FAILURE: "FETCH_DINOSAUR_FAILURE"
}
export default constants;